# Data preprocessing methods

Below are given the steps of data processing that need to be generally followed while handling data set for building the machine learning or deep learning models.

In [7]:

from sklearn.preprocessing import MinMaxScaler
# Read the data set using pandas and store in df
#df=pandas.read_csv( ‘data set file name', sep=',')
#array=df.values

# Read the input features from array into x
# Read the output features from the array into y
x = [[-1, 2], [-0.5, 6], [0, 10], [1, 18]]
scaler=MinMaxScaler(feature_range=(0,1))
rescaledX=scaler.fit_transform(x)



In [8]:
rescaledX

array([[ 0.  ,  0.  ],
       [ 0.25,  0.25],
       [ 0.5 ,  0.5 ],
       [ 1.  ,  1.  ]])

In [9]:
from sklearn.preprocessing import Normalizer
normscaler=Normalizer().fit(x)
normX=normscaler.transform(x)



In [10]:
normX

array([[-0.4472136 ,  0.89442719],
       [-0.08304548,  0.99654576],
       [ 0.        ,  1.        ],
       [ 0.05547002,  0.99846035]])

In [11]:
from sklearn.preprocessing import StandardScaler
standardScaler=StandardScaler().fit(x)
rescaledX=standardScaler.transform(x)



In [12]:
rescaledX

array([[-1.18321596, -1.18321596],
       [-0.50709255, -0.50709255],
       [ 0.16903085,  0.16903085],
       [ 1.52127766,  1.52127766]])

In [13]:
from sklearn.preprocessing import Binarizer
binarizerScalar=Binarizer(threshold=0.2).fit(x)
binaryX=binarizerScalar.transform(x)



In [14]:
binaryX

array([[ 0.,  1.],
       [ 0.,  1.],
       [ 0.,  1.],
       [ 1.,  1.]])

In [32]:
from sklearn.preprocessing import LabelEncoder
labelencoderInstance =LabelEncoder()
classesNames=['Havells','Philips','Syska','Eveready','Lloyd']
linstance = labelencoderInstance.fit(classesNames)

print (linstance)

LabelEncoder()


In [17]:
from sklearn.preprocessing import OneHotEncoder
encoderInstance=OneHotEncoder()
encoderInstance.fit([[1,1,2,2],
[1,6,3,8],
[1,4,9,7],
[4,0,4,5]
])



OneHotEncoder()

In [31]:
import numpy as np
from sklearn.impute import SimpleImputer
imputerInstance = SimpleImputer(missing_values = np.nan,strategy = 'mean')
imputer = imputerInstance.fit([[1, 2], [np.nan, 3], [7, 6]])
SimpleImputer()

X = [[1, 2], [np.nan, 3], [7, 6]]
print(imputer.transform(X))

[[ 1.  2.]
 [ 4.  3.]
 [ 7.  6.]]
